name: Fetch Updates

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Setup Dependencies"
        run: yarn
      - name: "Update"
        run: yarn update
        continue-on-error: true
      - name: "Print git status"
        run: git status
      - name: "Print git diff"
        run: git diff
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Update libraries
          branch: ${{ github.head_ref }}

          commit_user_name: elicwhite
          commit_user_email: github@eli-white.com
          commit_author: Eli White <github@eli-white.com>
